# workflow名称
name: build-and-deploy-frontend-project
# 对应第1步，表示develop分支的代码改动会触发该workflow。
on:
  push:
    branches:
      - develop
      
jobs:
  build-and-deploy:
    # 定义job运行环境，使用linux环境
    runs-on: ubuntu-latest
    steps:
    # 对应第2步，借助已有脚本拉取代码
    - name: Checkout
      uses: actions/checkout@master
      
    # 第3步的准备工作，先配置好node环境
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    # 对应第3步，执行打包命令
    - name: 'Build'
      run: |
        npm i
        npm run build
   
    # 对应第4、5步，配置参数登陆服务器+拷贝到指定目录
    - name: Deploy
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.REMOTE_HOST }} # 服务器IP
        username: ${{ secrets.REMOTE_USERNAME }} # 登陆服务器的用户名
        key: ${{ secrets.PRIVATE_KEY }} # 登陆服务器的密钥
        source: "./dist/"
        target: "path/to/target/
